name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjVmYmI3Y2ItYWVkOS00NDA3LThkN2ItN2RjMTJiZDQ0MDMyIiwidGVuYW50X2lkIjoiMzU3NDlkMTg1OTA2NzcwN2FlYTFkOTllYTUyMDBlMDhmZjQ5ZjU2NDlkMGM2MDdjYzI4NDdhZWMzZDA5YjJiNCIsImludGVybmFsX3NlY3JldCI6Ijg0ZjMxZDZjLWU1ODAtNGYyNy05Y2M0LWRmMzk4ZjZkYjQwYSJ9.gwsLfwjXf-AMq8UitocELyNad5obLSCFkWOGXpTjsjk"
JWT_SECRET = "mysecret"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1